### ISSUE TITLE
Spring clean 🌼

### ISSUE THREAD

**Issue by whmacken** [bcgov/CCISS#23]
There are many CCISS-related and CCISS-tangential repos out there. We need to delete those that are no longer relevant and potentially centralize those that are (e.g. as git submodules to [bcgov/CISS](https://github.com/bcgov/CCISS)

List of repos to check
- [x] [bcgov/Build_WNA_BGC_model](https://github.com/bcgov/Build_WNA_BGC_model) - checked and added as submodule to [bcgov/CCISS](https://github.com/bcgov/CCISS)
- [x] [whmacken/Build_USA_BEC](https://github.com/whmacken/Build_USA_BEC) - checked and added as submodule to [bcgov/CCISS](https://github.com/bcgov/CCISS)
- [ ] [kdaust/BC_HexGrid](https://github.com/kdaust/BC_HexGrid) - checked and added as submodule to [bcgov/CCISS](https://github.com/bcgov/CCISS); will be functionized and deleted  see https://github.com/bcgov/BC_HexGrid/issues/1
- [x] [whmacken/CCISS_Portfolio_Dataset_Alignment](https://github.com/whmacken/CCISS_Portfolio_Dataset_Alignment) - checked and added as submodule to [bcgov/CCISS](https://github.com/bcgov/CCISS)
- [x] [whmacken/CCISS_Reporter](https://github.com/whmacken/CCISS_Reporter) - checked and added as submodule to [bcgov/CCISS](https://github.com/bcgov/CCISS)
- [x] [bcgov/CCISS_spatial](https://github.com/bcgov/CCISS_spatial) - see https://github.com/bcgov/CCISS/issues/23#issuecomment-2070879254
- [x] [bcgov/CCISS_ShinyApp](https://github.com/bcgov/CCISS_ShinyApp) - see https://github.com/bcgov/CCISS/issues/23#issuecomment-2070879254
- [x] [bcgov/ccsummary-cciss](https://github.com/bcgov/ccsummary-cciss) - see https://github.com/bcgov/CCISS/issues/23#issuecomment-2070879254
- [x]  https://github.com/kdaust/EdatopicReview - transfer to bcgov/Build_SS_Edatope_shiny
- [ ]  https://github.com/whmacken/aSMR_X_rSMR - conversions between relative and actual SMR -> may become a function in a package like cissr
- [x]  https://github.com/whmacken/SIBEC_Modelled - very much under development, potentially related to CCISS. Will move to bcgov once a working point has been reached.
- [x]  https://github.com/whmacken/CCISS_Webtool - old app; deleted
- [x]  https://github.com/FLNRO-Smithers-Research/BGC-Climate-Summaries - probably old.
- [x]  https://github.com/FLNRO-Smithers-Research/PortfolioKiri
- [x]  https://github.com/FLNRO-Smithers-Research/BGC_Climates_Shiny - pulled into a tab of ByBEC. Archived.
- [x]  https://github.com/FLNRO-Smithers-Research/BigBECmodel - maintained. Scripts not related to CCISS
- [x]  https://github.com/FLNRO-Smithers-Research/ByBecApp - old (can be deleted) moved to https://github.com/bcgov/byBEC_shiny
- [x]  https://github.com/bcgov/byBEC_shiny - this is the new repo for the byBEC shiny app. Removed from FLNRO
- [ ]  https://github.com/FLNRO-Smithers-Research/Feasibility_RasterMaps - potentially involved/relevant? Might have been superceeded by more current code.
- [x] https://github.com/whmacken/2019_CCISS - contained the graphic scripts from the CCISS paper. Moved these scripts to ccissr for conversion into functions, and archived the original repo

**Comment by CeresBarros** [comment]
Please note that the following repos have all been re-created in [bcgov](https://github.com/bcgov/) and can be deleted.

- [FLNRO-Smithers-Research/Build_WNA_BGC_model](https://github.com/FLNRO-Smithers-Research/Build_WNA_BGC_model) 
-  [whmacken/Build_USA_BEC](https://github.com/whmacken/Build_USA_BEC) ->[bcgov/BGC_USA_Build](https://github.com/bcgov/BGC_USA_Build)
-  [kdaust/BC_HexGrid](https://github.com/kdaust/BC_HexGrid) 
-  [whmacken/CCISS_Portfolio_Dataset_Alignment](https://github.com/whmacken/CCISS_Portfolio_Dataset_Alignment)
-  [whmacken/CCISS_Reporter](https://github.com/whmacken/CCISS_Reporter)
- [whmacken/TreeSuitabilityPrediction](https://github.com/whmacken/TreeSuitabilityPrediction) -> (https://github.com/bcgov/Tree_Feas_Predict)

**Comment by CeresBarros** [comment]
@whmacken these have been identified as defunct repos, or have been moved to `bcgov`. Please delete :)
- [x]  https://github.com/whmacken/CCISS_Webtool - deleted
- [x] [FLNRO-Smithers-Research/Build_WNA_BGC_model](https://github.com/FLNRO-Smithers-Research/Build_WNA_BGC_model) - archived
- [x] [whmacken/Build_USA_BEC](https://github.com/whmacken/Build_USA_BEC) - deleted
- [ ] [kdaust/BC_HexGrid](https://github.com/kdaust/BC_HexGrid)
- [x] [whmacken/CCISS_Portfolio_Dataset_Alignment](https://github.com/whmacken/CCISS_Portfolio_Dataset_Alignment) - deleted
- [x] [whmacken/CCISS_Reporter](https://github.com/whmacken/CCISS_Reporter) - archived
- [x] [whmacken/TreesuitabilityPrediction](https://github.com/whmacken/TreeFeasibilityPrediction) - delected

**Comment by CeresBarros** [comment]
[bcgov/CCISS_spatial](https://github.com/bcgov/CCISS_spatial) - is/was an attempt at interacting with and processing CCISS maps on the fly from the database

[bcgov/ccsummary-cciss](https://github.com/bcgov/ccsummary-cciss) - is an obsolete repo that can be deleted.

[bcgov/CCISS_ShinyApp](https://github.com/bcgov/CCISS_ShinyApp) - currently has two apps in it that will need to be separated into two independent Shiny App repos - or alternatively merged into one single app

**Comment by CeresBarros** [comment]
Other repos that may be involved in CCISS workflow(s) and need to be checked for relevance and whether they need to be moved to [`bcgov`](https://github.com/bcgov) or deleted.

- [ ] https://github.com/kdaust/EdatopicReview - potentially related to CCISS
- [ ] https://github.com/whmacken/aSMR_X_rSMR
- [ ] https://github.com/whmacken/SIBEC_Modelled - very much under development, potentially related to CCISS
- [ ] https://github.com/whmacken/CCISS_Webtool - old app; can be deleted
- [ ] https://github.com/FLNRO-Smithers-Research/BGC-Climate-Summaries - probably old.
- [ ] https://github.com/FLNRO-Smithers-Research/PortfolioKiri
- [ ] https://github.com/FLNRO-Smithers-Research/BGC_Climates_Shiny - pulled into a tab of ByBEC
- [ ] https://github.com/FLNRO-Smithers-Research/BigBECmodel
- [ ] https://github.com/FLNRO-Smithers-Research/ByBecApp - old (can be deleted) moved to https://github.com/bcgov/byBEC_shiny
- [ ] https://github.com/bcgov/byBEC_shiny
- [ ] https://github.com/FLNRO-Smithers-Research/Feasibility_RasterMaps - potentially involved/relevant? Might have been superceeded by more current code.

**Comment by CeresBarros** [comment]
As preparation for our next sprint, checking with @whmacken, @cmahony and @kdaust if this issue has been fully dealt with and can be closed :)
