### ISSUE TITLE
Create "data GH repos"

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/CCISS#51]
We have identified a few data objects that need version control, a version release system and an automated QC flow.
For these objects, we will create new "data repositories" on GH -- being mindful that the individual size of each dataset _must_ be small (under 50MB).

[data object -> repo]

- [ ] BECdb -> **bcgov/SS_ssBC_data** (⭐ in https://github.com/bcgov/CCISS/issues/50)
- [ ] US site series -> **bcgov/SS_ssUS_data** (🔵 in https://github.com/bcgov/CCISS/issues/50)
- [ ] AB site series -> **bcgov/SS_ssAB_data** (➕ in https://github.com/bcgov/CCISS/issues/50)
- [ ] site series table -> **bcgov/SS_feasTables_data** (🔺in https://github.com/bcgov/CCISS/issues/50)
- [ ] edatopic table -> **bcgov/SS_feasTables_data** (🔺in https://github.com/bcgov/CCISS/issues/50)
- [ ] feasibility table -> **bcgov/SS_feasTables_data** (🔺in https://github.com/bcgov/CCISS/issues/50)
- [ ] CF reference guide -> **bcgov/SS_CFRG_data** (💙 in https://github.com/bcgov/CCISS/issues/50)
